scanning images removed exit code 1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -76,15 +76,15 @@ jobs :
           severity: 'CRITICAL,HIGH'
           
 
-      # - name: Fail the job on critical or high vulnerabilities
-      #   run: |
-      #        vulnerability_count=$(cat trivy-results.json | jq -r '.runs[0].results[] | select(.level == "error" or .level == "warning") | .ruleId' | sort | uniq -c | wc -l)
-      #        if [ "$vulnerability_count" -gt 0 ]; then
-      #        echo "Found $vulnerability_count vulnerabilities. Failing the job."
-      #        exit 1
-      #        else
-      #        echo "No critical or high vulnerabilities found."
-      #        fi
+      - name: Fail the job on critical or high vulnerabilities
+        run: |
+             vulnerability_count=$(cat trivy-results.json | jq -r '.runs[0].results[] | select(.level == "error" or .level == "warning") | .ruleId' | sort | uniq -c | wc -l)
+             if [ "$vulnerability_count" -gt 0 ]; then
+             echo "Found $vulnerability_count vulnerabilities. Failing the job."
+             exit 1
+             else
+             echo "No critical or high vulnerabilities found."
+             fi
         
       # - name: Upload Trivy scan results to GitHub Security tab
       #   uses: github/codeql-action/upload-sarif@v2
