fail job if quality gate gets failed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,6 +49,21 @@ jobs :
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
 
+      - name: Check Code Coverage
+        run: |
+          # Fetch Quality Gates status using SonarQube API
+          status=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
+
+          # Check if Quality Gates status is not "OK" (i.e., if it failed)
+          if [ "$status" != "OK" ]; then
+            echo "SonarQube Quality Gates failed."
+            exit 1
+          fi
+        # env:
+        #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+        
  # Secret Scanning
       # - name: Secret Scanning
       #   uses: secret-scanner/action@0.0.2
