added check for quality gate using actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,19 +49,37 @@ jobs :
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
 
-      - name: Check Code Coverage
-        run: |
-          # Fetch Quality Gates status using SonarQube API
-          status=$(curl -s -u 682af0d2cbf807095fe63d2cf0893f3f698df8ab --max-time 30 "http://172.27.59.127:9000/api/qualitygates/project_status?projectKey=GITHUB_ACTION_TR%3Amaster" | jq -r '.projectStatus.status')
+      # - name: Check Code Coverage
+      #   run: |
+      #     # Fetch Quality Gates status using SonarQube API
+      #     status=$(curl -s -u 682af0d2cbf807095fe63d2cf0893f3f698df8ab --max-time 30 "http://172.27.59.127:9000/api/qualitygates/project_status?projectKey=GITHUB_ACTION_TR%3Amaster" | jq -r '.projectStatus.status')
 
-          # Check if Quality Gates status is not "OK" (i.e., if it failed)
-          if [ "$status" != "OK" ]; then
-            echo "SonarQube Quality Gates failed."
-            exit 1
-          fi
+      #     # Check if Quality Gates status is not "OK" (i.e., if it failed)
+      #     if [ "$status" != "OK" ]; then
+      #       echo "SonarQube Quality Gates failed."
+      #       exit 1
+      #     fi
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+
+# Check the Quality Gate status.
+      - name: SonarQube Quality Gate check
+        id: sonarqube-quality-gate-check
+        uses: sonarsource/sonarqube-quality-gate-action@master
+        with:
+          scanMetadataReportFile: target/sonar/report-task.txt
+      # Force to fail step after specific time.
+        timeout-minutes: 5
         env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL
+
+    # Optionally you can use the output from the Quality Gate in another step.
+    # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
+      - name: "Example show SonarQube Quality Gate Status value"
+        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
 
         
  # Secret Scanning
